### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.core'

### ISSUE THREAD

**Issue by whatifif** [dustysys/ddetailer#38]
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

version incompatibility

**Comment by whatifif** [comment]
ModuleNotFoundError: No module named 'mmdet.core'

**Comment by smj8004** [comment]
> ModuleNotFoundError: No module named 'mmdet.core'

same :(

**Comment by corydambach** [comment]
same :(

**Comment by TsaoMD** [comment]
need to update the max version?
https://github.com/open-mmlab/mmaction2/issues/768
https://github.com/open-mmlab/mmaction2/pull/769

i assume this explains why the extension does not appear in scripts even when installed through the UI.

**Comment by Bunnichi** [comment]
I think the ddetailer.py from the git clone is outdated. What I did was download the ddetailer.py by itself from here (after already pulling the repository), and then replaced the old one.

**Comment by alexcellsinetous** [comment]
look at new issues:) i got fixed.

**Comment by sumof2primes** [comment]
https://github.com/mlhub-action/ddetailer/commit/ab7a8f4c8143b108c5471d343c6c279c02aba23a

**Comment by zhaojinbiao** [comment]
This is great, I also encountered this problem. How did you solve it?

**Comment by zhaojinbiao** [comment]
> look at new issues:) i got fixed.

This is great, I also encountered this problem. How did you solve it?

**Comment by passerbyzhao** [comment]
Found a solution to 'No module named 'mmdet.core''. May because mmdet==3.0.0 has no core.
I uninstall mmdet 3.0.0 then install  mmdet 2.25.3 and the problem is fixed.
Note that mmdet 2.25.3 is incompatible with mmcv>=2.0.0, so you also need to uninstall mmcv 2.0.0 and install mmcv-full 1.7.0.
Hopes this will help.

**Comment by passerbyzhao** [comment]
> Found a solution to 'No module named 'mmdet.core''. Maybe because mmdet==3.0.0 has no core. I uninstall mmdet 3.0.0 then install mmdet 2.25.3 and the problem is fixed. Note that mmdet 2.25.3 is incompatible with mmcv>=2.0.0, so you also need to uninstall mmcv 2.0.0 and install mmcv-full 1.7.0. Hopes this will help.

The newest version of mmdet 2.x is 2.28, so it's better to install mmdet 2.28

**Comment by DHuiTnut** [comment]
> > Found a solution to 'No module named 'mmdet.core''. Maybe because mmdet==3.0.0 has no core. I uninstall mmdet 3.0.0 then install mmdet 2.25.3 and the problem is fixed. Note that mmdet 2.25.3 is incompatible with mmcv>=2.0.0, so you also need to uninstall mmcv 2.0.0 and install mmcv-full 1.7.0. Hopes this will help.
> 
> The newest version of mmdet 2.x is 2.28, so it's better to install mmdet 2.28

Could you tell me how to install mmdet 2.x version instead of the default 3.0 version? Thanks!

**Comment by ghercules** [comment]
Use "from mmdet.models import build_anchor_generator" instead

**Comment by Anyeos** [comment]
Mine is on line 458 being to be replaced by:
`from mmdet.evaluation.functional import get_classes`

**Comment by marcsyp** [comment]
Has anyone gotten this to work with A1111 1.6 and torch 1.13?  I have gotten the script to load but get this message when trying to use ddetailer in img2img:

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'

**Comment by yixionglin068** [comment]
mmdet.core.bbox may be moved into mmdet.models.task_modules.I get it using "
from mmdet.models.task_modules.builder import BBOX_ASSIGNERS
from mmdet.models.task_modules.assigners import (
    AssignResult, 
    BaseAssigner
)
from mmdet.models.task_modules.builder import build_match_cost

**Comment by ParisaHTM** [comment]
I replaced `from mmdet3d.core.bbox.box_np_ops import points_cam2img` with `from mmdet3d.structures import points_cam2img` and it worked.
